# Generated by Django 4.2.7 on 2024-01-01 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_fillfrom_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fillfrom',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
