# Generated by Django 4.2.7 on 2024-01-01 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_fillfrom_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fillfrom',
            name='roll_number',
        ),
    ]
