# Generated by Django 4.2.7 on 2024-01-01 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_fillfrom_roll_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fillfrom',
            name='choice_department',
        ),
    ]
