# Generated by Django 4.2.7 on 2024-01-05 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_fillfrom_filled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fillfrom',
            name='filled',
        ),
        migrations.CreateModel(
            name='Onetime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filled', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
