# Generated by Django 4.2.7 on 2024-01-06 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_fillfrom_filled_onetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='button_clicked',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Onetime',
        ),
    ]
