# Generated by Django 4.2.7 on 2024-01-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_useraction_delete_onetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='explain',
            field=models.CharField(default=1, max_length=900),
            preserve_default=False,
        ),
    ]
