# Generated by Django 4.2.7 on 2024-01-11 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_pdfdocument_explain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fillfrom',
            name='Course_name',
        ),
        migrations.AddField(
            model_name='fillfrom',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fillfrom',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.department'),
            preserve_default=False,
        ),
    ]
