# Generated by Django 4.2.7 on 2024-01-11 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_userclick'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userclick',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserAction',
        ),
        migrations.DeleteModel(
            name='UserClick',
        ),
    ]
