# Generated by Django 4.2.7 on 2024-01-11 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_fillfrom_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fillfrom',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.course'),
        ),
    ]
