# Generated by Django 5.0.1 on 2024-01-27 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_feedback_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
    ]
