# Generated by Django 5.0.1 on 2024-01-27 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_feedback_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='user',
            new_name='submitter',
        ),
    ]
