# Generated by Django 5.0.1 on 2024-01-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_feedbacks'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='link',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
