# Generated by Django 5.0.1 on 2024-01-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_pdfdocument_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfdocument',
            name='explain',
            field=models.CharField(blank=True, max_length=900),
        ),
        migrations.AlterField(
            model_name='pdfdocument',
            name='link',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='pdfdocument',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to='pdf_documents/'),
        ),
        migrations.AlterField(
            model_name='pdfdocument',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
