# Generated by Django 5.0.1 on 2024-01-27 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_rename_program_memo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memo',
            old_name='description1',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='memo',
            old_name='title1',
            new_name='title',
        ),
    ]
