# Generated by Django 5.0.1 on 2024-01-28 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_alter_yourmodel_submitter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='course',
        ),
        migrations.RemoveField(
            model_name='yourmodel',
            name='submitter',
        ),
        migrations.DeleteModel(
            name='Studentdetails',
        ),
        migrations.DeleteModel(
            name='video',
        ),
        migrations.DeleteModel(
            name='YourModel',
        ),
    ]
