# Generated by Django 5.0.1 on 2024-02-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_pdfdocument_link_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='course_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
