# Generated by Django 5.0.1 on 2024-02-09 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_pdfdocument_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfdocument',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to='pdf_document/'),
        ),
    ]
